### ISSUE TITLE
Issue with enums

### ISSUE THREAD

**Issue by andrei9669** [ritchieanesco/json-schema-yup-transform#57] opened 2022-04-12 08:44 UTC
`"json-schema-yup-transformer": "1.6.8"`

When I updated from version 1.6.4 to version 1.6.8, I get this sort of error
```
Uncaught TypeError: Cannot read properties of undefined (reading 'STRING')
    at Object../node_modules/json-schema-yup-transformer/dist/schema/utils.js (utils.ts:28:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object../node_modules/json-schema-yup-transformer/dist/schema/index.js (index.ts:2:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object../node_modules/json-schema-yup-transformer/dist/yup/addMethods/array.js (array.ts:9:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object../node_modules/json-schema-yup-transformer/dist/yup/addMethods/index.js (index.ts:2:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object../node_modules/json-schema-yup-transformer/dist/yup/builder/index.js (index.ts:6:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object../node_modules/json-schema-yup-transformer/dist/yup/index.js (index.ts:1:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Object../node_modules/json-schema-yup-transformer/dist/index.js (index.ts:3:1)
    at __webpack_require__ (bootstrap:856:1)
    at fn (bootstrap:150:1)
    at Module.<anonymous> (utils.ts:44:1)
    .....(local code)
```
which roughly says that DataTypes is undefined
https://github.com/ritchieanesco/json-schema-yup-transform/blob/f4932398e71f567483fe914a35aebd19fd3f13dc/src/schema/utils.ts#L28

**Comment by leonbloy** [comment] 2022-04-12 22:03
Same here.
Worked with 1.6.7

**Comment by MahdiMontgomery** [comment] 2022-04-18 16:58
+1 also having this issue

**Comment by ritchieanesco** [comment] 2022-08-14 10:45
Duplicate of #60. See comment.

**Closed as completed by ritchieanesco** 2022-08-14 10:45 UTC
